### ISSUE TITLE
Add description of member on messages

### ISSUE THREAD

**Issue by Troski** [astuff/astuff_sensor_msgs#30]
some members of some messages are quite ambiguous, and hard to know what they are. for example on ESRTrack.msg "track_status". It would be helpful to comment some of these, or add constants that can be used.

**Comment by JWhitleyAStuff** [comment]
@Troski - thank you for the suggestion. We will add commenting all of the messages to our development items.

**Comment by icolwell-as** [comment]
Descriptions in the ROS messages will not be provided since it is Delphi's IP.
If you are an AutonomouStuff customer and wish to understand the details of the various ESR messages, you should have received a PDF user manual for the ESR with your purchase. 
Please reach out to support if you are a customer and need access to this user manual: https://autonomoustuff.com/support
