### ISSUE TITLE
Having trouble to communicate using Ethernet

### ISSUE THREAD

**Issue by pedrobagatin** [astuff/astuff_sensor_msgs#33]
I know this is not the right place to ask this kind of question but couldn't find any other way.

I have a Delphi ESR 2.5 (24 V) radar which works perfectly using CAN, but can't ping using Ethernet.

Is there any way to know if there is a hardware problem? 

Does it only work with specific USB - Ethernet adapters (the one described in the manual)? 

[Asked question in ROS forum too](https://answers.ros.org/question/322326/delphi-esr-ethernet-connection/?comment=322343#post-id-322343)

**Comment by JWhitleyAStuff** [comment]
@pedrobagatin - I'm sorry you have had to search around for a solution to this. Since this is specific to a piece of hardware that only AS sells, would you mind sending this question to support@autonomoustuff.com? It allows us to track a ticket internally and get you routed to the correct person. Thanks!
