### ISSUE TITLE
Consider moving pacmod_msgs into the pacmod3 driver repo

### ISSUE THREAD

**Issue by icolwell-as** [astuff/astuff_sensor_msgs#59]
Much like all other ROS drivers, consider moving the message package into the same repo as the driver package.

**Comment by JWhitleyWork** [comment]
There's no real technical benefit or detrement to having them in different repos. It's just a "logical grouping" thing. However, for the other messages, I highly recommend leaving them here so they are open-source rather than adding them to the repos for the closed-source drivers. People do use them. For example, https://github.com/search?q=delphi_esr_msgs&type=code, https://github.com/search?q=derived_object_msgs&type=code, https://github.com/search?q=ibeo_msgs&type=code, etc.

**Comment by icolwell-as** [comment]
Starting with Ubuntu 20.04, `pacmod_msgs` has turned into `pacmod3_msgs` and it is located in it's own repo:
https://github.com/astuff/pacmod3_msgs
